// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZOpGOcjbkOTp5My8aBYSSQb6CrXd_Dpc',
    appId: '1:637790328645:web:f900dbf2312dcef6cbd02c',
    messagingSenderId: '637790328645',
    projectId: 'reddit-clone-4078b',
    authDomain: 'reddit-clone-4078b.firebaseapp.com',
    storageBucket: 'reddit-clone-4078b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIMWNlaecFaLkaBGXIqaEg2aTbrYdTbD0',
    appId: '1:637790328645:android:ef84348a1a4a4630cbd02c',
    messagingSenderId: '637790328645',
    projectId: 'reddit-clone-4078b',
    storageBucket: 'reddit-clone-4078b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOcdqSO5x1AUsz58gHP2Yjpy7fDTlcc4',
    appId: '1:637790328645:ios:41f3818b85042f85cbd02c',
    messagingSenderId: '637790328645',
    projectId: 'reddit-clone-4078b',
    storageBucket: 'reddit-clone-4078b.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
